root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/ocman ."
  bin = "./tmp/ocman"
  full_bin = "./tmp/ocman -addr 0.0.0.0:8229"
  include_ext = ["go"]
  exclude_dir = ["tmp", "frontend", "internal/server/static"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
