// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: internal/remote/proto/remote.proto

package remotepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ocman_Hello_FullMethodName                  = "/ocman.remote.v1.Ocman/Hello"
	Ocman_Sessions_FullMethodName               = "/ocman.remote.v1.Ocman/Sessions"
	Ocman_Session_FullMethodName                = "/ocman.remote.v1.Ocman/Session"
	Ocman_SessionsInactiveBefore_FullMethodName = "/ocman.remote.v1.Ocman/SessionsInactiveBefore"
	Ocman_SessionChanges_FullMethodName         = "/ocman.remote.v1.Ocman/SessionChanges"
	Ocman_SessionInfo_FullMethodName            = "/ocman.remote.v1.Ocman/SessionInfo"
	Ocman_AgentCatalog_FullMethodName           = "/ocman.remote.v1.Ocman/AgentCatalog"
	Ocman_SlashCommands_FullMethodName          = "/ocman.remote.v1.Ocman/SlashCommands"
	Ocman_SessionModels_FullMethodName          = "/ocman.remote.v1.Ocman/SessionModels"
	Ocman_ListPermissions_FullMethodName        = "/ocman.remote.v1.Ocman/ListPermissions"
	Ocman_ListQuestions_FullMethodName          = "/ocman.remote.v1.Ocman/ListQuestions"
	Ocman_PermissionRules_FullMethodName        = "/ocman.remote.v1.Ocman/PermissionRules"
	Ocman_Capabilities_FullMethodName           = "/ocman.remote.v1.Ocman/Capabilities"
	Ocman_Owns_FullMethodName                   = "/ocman.remote.v1.Ocman/Owns"
	Ocman_SendMessage_FullMethodName            = "/ocman.remote.v1.Ocman/SendMessage"
	Ocman_ExecuteCommand_FullMethodName         = "/ocman.remote.v1.Ocman/ExecuteCommand"
	Ocman_RunShell_FullMethodName               = "/ocman.remote.v1.Ocman/RunShell"
	Ocman_RespondPermission_FullMethodName      = "/ocman.remote.v1.Ocman/RespondPermission"
	Ocman_RespondQuestion_FullMethodName        = "/ocman.remote.v1.Ocman/RespondQuestion"
	Ocman_RejectQuestion_FullMethodName         = "/ocman.remote.v1.Ocman/RejectQuestion"
	Ocman_Abort_FullMethodName                  = "/ocman.remote.v1.Ocman/Abort"
	Ocman_RenameSession_FullMethodName          = "/ocman.remote.v1.Ocman/RenameSession"
	Ocman_SetPermissionRules_FullMethodName     = "/ocman.remote.v1.Ocman/SetPermissionRules"
	Ocman_Compact_FullMethodName                = "/ocman.remote.v1.Ocman/Compact"
	Ocman_ForkSession_FullMethodName            = "/ocman.remote.v1.Ocman/ForkSession"
	Ocman_MoveSession_FullMethodName            = "/ocman.remote.v1.Ocman/MoveSession"
	Ocman_CreateSession_FullMethodName          = "/ocman.remote.v1.Ocman/CreateSession"
	Ocman_StreamEvents_FullMethodName           = "/ocman.remote.v1.Ocman/StreamEvents"
	Ocman_GitInfo_FullMethodName                = "/ocman.remote.v1.Ocman/GitInfo"
	Ocman_GitDiff_FullMethodName                = "/ocman.remote.v1.Ocman/GitDiff"
	Ocman_GitBranches_FullMethodName            = "/ocman.remote.v1.Ocman/GitBranches"
	Ocman_GitCheckout_FullMethodName            = "/ocman.remote.v1.Ocman/GitCheckout"
	Ocman_ListWorktrees_FullMethodName          = "/ocman.remote.v1.Ocman/ListWorktrees"
	Ocman_WorktreeDefaultBaseRef_FullMethodName = "/ocman.remote.v1.Ocman/WorktreeDefaultBaseRef"
	Ocman_CreateWorktreeSession_FullMethodName  = "/ocman.remote.v1.Ocman/CreateWorktreeSession"
	Ocman_RemoveWorktree_FullMethodName         = "/ocman.remote.v1.Ocman/RemoveWorktree"
	Ocman_LaunchTmux_FullMethodName             = "/ocman.remote.v1.Ocman/LaunchTmux"
	Ocman_EnsureProjectOpencode_FullMethodName  = "/ocman.remote.v1.Ocman/EnsureProjectOpencode"
	Ocman_RestartProjectOpencode_FullMethodName = "/ocman.remote.v1.Ocman/RestartProjectOpencode"
	Ocman_TmuxSessions_FullMethodName           = "/ocman.remote.v1.Ocman/TmuxSessions"
	Ocman_HostCapabilities_FullMethodName       = "/ocman.remote.v1.Ocman/HostCapabilities"
	Ocman_TermWindows_FullMethodName            = "/ocman.remote.v1.Ocman/TermWindows"
	Ocman_TermCreateWindow_FullMethodName       = "/ocman.remote.v1.Ocman/TermCreateWindow"
	Ocman_TermKillWindow_FullMethodName         = "/ocman.remote.v1.Ocman/TermKillWindow"
	Ocman_TerminalStream_FullMethodName         = "/ocman.remote.v1.Ocman/TerminalStream"
	Ocman_Projects_FullMethodName               = "/ocman.remote.v1.Ocman/Projects"
	Ocman_WatchProjects_FullMethodName          = "/ocman.remote.v1.Ocman/WatchProjects"
)

// OcmanClient is the client API for Ocman service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ocman is the hub<->remote gRPC contract for multi-remote support.
//
// Per architecture AD-11, rich nested types (db.Session, SessionDetail,
// LivePrompt, etc.) travel as JSON bytes inside JsonResp/JsonReq because
// the two ends are the same codebase/version (guarded by the Hello
// protocol-version handshake, AD-12). Scalar routing fields (platform,
// session_id, dir, since, limit) are typed proto fields.
//
// PlatformRef / SessionRef carry the BASE platform id (the hub strips
// the "r-<remoteID>:" prefix before calling). All RPCs require the
// bearer token (AD-4).
type OcmanClient interface {
	// Handshake: exchanged once after dialing (AD-12).
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
	// --- Session reads ---
	Sessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*JsonResp, error)
	Session(ctx context.Context, in *SessionReq, opts ...grpc.CallOption) (*JsonResp, error)
	SessionsInactiveBefore(ctx context.Context, in *CutoffReq, opts ...grpc.CallOption) (*JsonResp, error)
	SessionChanges(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	SessionInfo(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	AgentCatalog(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	SlashCommands(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	SessionModels(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	ListPermissions(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	ListQuestions(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	PermissionRules(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error)
	Capabilities(ctx context.Context, in *PlatformRef, opts ...grpc.CallOption) (*JsonResp, error)
	Owns(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*OwnsResp, error)
	// --- Session mutations (JSON request payload) ---
	SendMessage(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	ExecuteCommand(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	RunShell(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	RespondPermission(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	RespondQuestion(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	RejectQuestion(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	Abort(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	RenameSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	SetPermissionRules(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	Compact(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	ForkSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	MoveSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error)
	CreateSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	// --- Streaming events (tunneled to hub SSE) ---
	StreamEvents(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventChunk], error)
	// --- Host services (directory-scoped) ---
	GitInfo(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	GitDiff(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	GitBranches(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	GitCheckout(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error)
	ListWorktrees(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	WorktreeDefaultBaseRef(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	CreateWorktreeSession(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	RemoveWorktree(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error)
	LaunchTmux(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	EnsureProjectOpencode(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	RestartProjectOpencode(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	TmuxSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error)
	HostCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error)
	// In-app terminal windows (directory-scoped, executed on the owner).
	TermWindows(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	TermCreateWindow(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error)
	TermKillWindow(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error)
	// TerminalStream bridges a browser xterm.js WebSocket to a PTY
	// attached to the owner's tmux. Client->server frames carry keystrokes
	// and resize control; server->client frames carry PTY output.
	TerminalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TermClientMsg, TermServerMsg], error)
	// --- Project inventory ---
	Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error)
	WatchProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JsonResp], error)
}

type ocmanClient struct {
	cc grpc.ClientConnInterface
}

func NewOcmanClient(cc grpc.ClientConnInterface) OcmanClient {
	return &ocmanClient{cc}
}

func (c *ocmanClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, Ocman_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Sessions(ctx context.Context, in *SessionsReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_Sessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Session(ctx context.Context, in *SessionReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_Session_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SessionsInactiveBefore(ctx context.Context, in *CutoffReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_SessionsInactiveBefore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SessionChanges(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_SessionChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SessionInfo(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_SessionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) AgentCatalog(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_AgentCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SlashCommands(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_SlashCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SessionModels(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_SessionModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) ListPermissions(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) ListQuestions(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_ListQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) PermissionRules(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_PermissionRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Capabilities(ctx context.Context, in *PlatformRef, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Owns(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*OwnsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnsResp)
	err := c.cc.Invoke(ctx, Ocman_Owns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SendMessage(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) ExecuteCommand(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RunShell(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RunShell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RespondPermission(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RespondPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RespondQuestion(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RespondQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RejectQuestion(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RejectQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Abort(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RenameSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RenameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) SetPermissionRules(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_SetPermissionRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) Compact(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) ForkSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_ForkSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) MoveSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_MoveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) CreateSession(ctx context.Context, in *PlatformJsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) StreamEvents(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ocman_ServiceDesc.Streams[0], Ocman_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRef, EventChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_StreamEventsClient = grpc.ServerStreamingClient[EventChunk]

func (c *ocmanClient) GitInfo(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_GitInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) GitDiff(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_GitDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) GitBranches(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_GitBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) GitCheckout(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_GitCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) ListWorktrees(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_ListWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) WorktreeDefaultBaseRef(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_WorktreeDefaultBaseRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) CreateWorktreeSession(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_CreateWorktreeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RemoveWorktree(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_RemoveWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) LaunchTmux(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_LaunchTmux_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) EnsureProjectOpencode(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_EnsureProjectOpencode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) RestartProjectOpencode(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_RestartProjectOpencode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) TmuxSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_TmuxSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) HostCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_HostCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) TermWindows(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_TermWindows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) TermCreateWindow(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_TermCreateWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) TermKillWindow(ctx context.Context, in *JsonReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Ocman_TermKillWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) TerminalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TermClientMsg, TermServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ocman_ServiceDesc.Streams[1], Ocman_TerminalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TermClientMsg, TermServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_TerminalStreamClient = grpc.BidiStreamingClient[TermClientMsg, TermServerMsg]

func (c *ocmanClient) Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResp)
	err := c.cc.Invoke(ctx, Ocman_Projects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocmanClient) WatchProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JsonResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ocman_ServiceDesc.Streams[2], Ocman_WatchProjects_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, JsonResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_WatchProjectsClient = grpc.ServerStreamingClient[JsonResp]

// OcmanServer is the server API for Ocman service.
// All implementations must embed UnimplementedOcmanServer
// for forward compatibility.
//
// Ocman is the hub<->remote gRPC contract for multi-remote support.
//
// Per architecture AD-11, rich nested types (db.Session, SessionDetail,
// LivePrompt, etc.) travel as JSON bytes inside JsonResp/JsonReq because
// the two ends are the same codebase/version (guarded by the Hello
// protocol-version handshake, AD-12). Scalar routing fields (platform,
// session_id, dir, since, limit) are typed proto fields.
//
// PlatformRef / SessionRef carry the BASE platform id (the hub strips
// the "r-<remoteID>:" prefix before calling). All RPCs require the
// bearer token (AD-4).
type OcmanServer interface {
	// Handshake: exchanged once after dialing (AD-12).
	Hello(context.Context, *HelloReq) (*HelloResp, error)
	// --- Session reads ---
	Sessions(context.Context, *SessionsReq) (*JsonResp, error)
	Session(context.Context, *SessionReq) (*JsonResp, error)
	SessionsInactiveBefore(context.Context, *CutoffReq) (*JsonResp, error)
	SessionChanges(context.Context, *SessionRef) (*JsonResp, error)
	SessionInfo(context.Context, *SessionRef) (*JsonResp, error)
	AgentCatalog(context.Context, *SessionRef) (*JsonResp, error)
	SlashCommands(context.Context, *SessionRef) (*JsonResp, error)
	SessionModels(context.Context, *SessionRef) (*JsonResp, error)
	ListPermissions(context.Context, *SessionRef) (*JsonResp, error)
	ListQuestions(context.Context, *SessionRef) (*JsonResp, error)
	PermissionRules(context.Context, *SessionRef) (*JsonResp, error)
	Capabilities(context.Context, *PlatformRef) (*JsonResp, error)
	Owns(context.Context, *SessionRef) (*OwnsResp, error)
	// --- Session mutations (JSON request payload) ---
	SendMessage(context.Context, *PlatformJsonReq) (*Empty, error)
	ExecuteCommand(context.Context, *PlatformJsonReq) (*Empty, error)
	RunShell(context.Context, *PlatformJsonReq) (*Empty, error)
	RespondPermission(context.Context, *PlatformJsonReq) (*Empty, error)
	RespondQuestion(context.Context, *PlatformJsonReq) (*Empty, error)
	RejectQuestion(context.Context, *PlatformJsonReq) (*Empty, error)
	Abort(context.Context, *PlatformJsonReq) (*Empty, error)
	RenameSession(context.Context, *PlatformJsonReq) (*Empty, error)
	SetPermissionRules(context.Context, *PlatformJsonReq) (*Empty, error)
	Compact(context.Context, *PlatformJsonReq) (*Empty, error)
	ForkSession(context.Context, *PlatformJsonReq) (*JsonResp, error)
	MoveSession(context.Context, *PlatformJsonReq) (*Empty, error)
	CreateSession(context.Context, *PlatformJsonReq) (*JsonResp, error)
	// --- Streaming events (tunneled to hub SSE) ---
	StreamEvents(*SessionRef, grpc.ServerStreamingServer[EventChunk]) error
	// --- Host services (directory-scoped) ---
	GitInfo(context.Context, *JsonReq) (*JsonResp, error)
	GitDiff(context.Context, *JsonReq) (*JsonResp, error)
	GitBranches(context.Context, *JsonReq) (*JsonResp, error)
	GitCheckout(context.Context, *JsonReq) (*Empty, error)
	ListWorktrees(context.Context, *JsonReq) (*JsonResp, error)
	WorktreeDefaultBaseRef(context.Context, *JsonReq) (*JsonResp, error)
	CreateWorktreeSession(context.Context, *JsonReq) (*JsonResp, error)
	RemoveWorktree(context.Context, *JsonReq) (*Empty, error)
	LaunchTmux(context.Context, *JsonReq) (*JsonResp, error)
	EnsureProjectOpencode(context.Context, *JsonReq) (*JsonResp, error)
	RestartProjectOpencode(context.Context, *JsonReq) (*JsonResp, error)
	TmuxSessions(context.Context, *Empty) (*JsonResp, error)
	HostCapabilities(context.Context, *Empty) (*JsonResp, error)
	// In-app terminal windows (directory-scoped, executed on the owner).
	TermWindows(context.Context, *JsonReq) (*JsonResp, error)
	TermCreateWindow(context.Context, *JsonReq) (*JsonResp, error)
	TermKillWindow(context.Context, *JsonReq) (*Empty, error)
	// TerminalStream bridges a browser xterm.js WebSocket to a PTY
	// attached to the owner's tmux. Client->server frames carry keystrokes
	// and resize control; server->client frames carry PTY output.
	TerminalStream(grpc.BidiStreamingServer[TermClientMsg, TermServerMsg]) error
	// --- Project inventory ---
	Projects(context.Context, *Empty) (*JsonResp, error)
	WatchProjects(*Empty, grpc.ServerStreamingServer[JsonResp]) error
	mustEmbedUnimplementedOcmanServer()
}

// UnimplementedOcmanServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOcmanServer struct{}

func (UnimplementedOcmanServer) Hello(context.Context, *HelloReq) (*HelloResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedOcmanServer) Sessions(context.Context, *SessionsReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Sessions not implemented")
}
func (UnimplementedOcmanServer) Session(context.Context, *SessionReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedOcmanServer) SessionsInactiveBefore(context.Context, *CutoffReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionsInactiveBefore not implemented")
}
func (UnimplementedOcmanServer) SessionChanges(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionChanges not implemented")
}
func (UnimplementedOcmanServer) SessionInfo(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionInfo not implemented")
}
func (UnimplementedOcmanServer) AgentCatalog(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentCatalog not implemented")
}
func (UnimplementedOcmanServer) SlashCommands(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SlashCommands not implemented")
}
func (UnimplementedOcmanServer) SessionModels(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionModels not implemented")
}
func (UnimplementedOcmanServer) ListPermissions(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedOcmanServer) ListQuestions(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuestions not implemented")
}
func (UnimplementedOcmanServer) PermissionRules(context.Context, *SessionRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PermissionRules not implemented")
}
func (UnimplementedOcmanServer) Capabilities(context.Context, *PlatformRef) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedOcmanServer) Owns(context.Context, *SessionRef) (*OwnsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Owns not implemented")
}
func (UnimplementedOcmanServer) SendMessage(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedOcmanServer) ExecuteCommand(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedOcmanServer) RunShell(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RunShell not implemented")
}
func (UnimplementedOcmanServer) RespondPermission(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondPermission not implemented")
}
func (UnimplementedOcmanServer) RespondQuestion(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondQuestion not implemented")
}
func (UnimplementedOcmanServer) RejectQuestion(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectQuestion not implemented")
}
func (UnimplementedOcmanServer) Abort(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedOcmanServer) RenameSession(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSession not implemented")
}
func (UnimplementedOcmanServer) SetPermissionRules(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPermissionRules not implemented")
}
func (UnimplementedOcmanServer) Compact(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedOcmanServer) ForkSession(context.Context, *PlatformJsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ForkSession not implemented")
}
func (UnimplementedOcmanServer) MoveSession(context.Context, *PlatformJsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveSession not implemented")
}
func (UnimplementedOcmanServer) CreateSession(context.Context, *PlatformJsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedOcmanServer) StreamEvents(*SessionRef, grpc.ServerStreamingServer[EventChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedOcmanServer) GitInfo(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GitInfo not implemented")
}
func (UnimplementedOcmanServer) GitDiff(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GitDiff not implemented")
}
func (UnimplementedOcmanServer) GitBranches(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GitBranches not implemented")
}
func (UnimplementedOcmanServer) GitCheckout(context.Context, *JsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method GitCheckout not implemented")
}
func (UnimplementedOcmanServer) ListWorktrees(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedOcmanServer) WorktreeDefaultBaseRef(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WorktreeDefaultBaseRef not implemented")
}
func (UnimplementedOcmanServer) CreateWorktreeSession(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorktreeSession not implemented")
}
func (UnimplementedOcmanServer) RemoveWorktree(context.Context, *JsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorktree not implemented")
}
func (UnimplementedOcmanServer) LaunchTmux(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchTmux not implemented")
}
func (UnimplementedOcmanServer) EnsureProjectOpencode(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureProjectOpencode not implemented")
}
func (UnimplementedOcmanServer) RestartProjectOpencode(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartProjectOpencode not implemented")
}
func (UnimplementedOcmanServer) TmuxSessions(context.Context, *Empty) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TmuxSessions not implemented")
}
func (UnimplementedOcmanServer) HostCapabilities(context.Context, *Empty) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HostCapabilities not implemented")
}
func (UnimplementedOcmanServer) TermWindows(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TermWindows not implemented")
}
func (UnimplementedOcmanServer) TermCreateWindow(context.Context, *JsonReq) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TermCreateWindow not implemented")
}
func (UnimplementedOcmanServer) TermKillWindow(context.Context, *JsonReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TermKillWindow not implemented")
}
func (UnimplementedOcmanServer) TerminalStream(grpc.BidiStreamingServer[TermClientMsg, TermServerMsg]) error {
	return status.Error(codes.Unimplemented, "method TerminalStream not implemented")
}
func (UnimplementedOcmanServer) Projects(context.Context, *Empty) (*JsonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Projects not implemented")
}
func (UnimplementedOcmanServer) WatchProjects(*Empty, grpc.ServerStreamingServer[JsonResp]) error {
	return status.Error(codes.Unimplemented, "method WatchProjects not implemented")
}
func (UnimplementedOcmanServer) mustEmbedUnimplementedOcmanServer() {}
func (UnimplementedOcmanServer) testEmbeddedByValue()               {}

// UnsafeOcmanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OcmanServer will
// result in compilation errors.
type UnsafeOcmanServer interface {
	mustEmbedUnimplementedOcmanServer()
}

func RegisterOcmanServer(s grpc.ServiceRegistrar, srv OcmanServer) {
	// If the following call panics, it indicates UnimplementedOcmanServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ocman_ServiceDesc, srv)
}

func _Ocman_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Sessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Sessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Sessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Sessions(ctx, req.(*SessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Session_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Session(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Session_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Session(ctx, req.(*SessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SessionsInactiveBefore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CutoffReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SessionsInactiveBefore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SessionsInactiveBefore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SessionsInactiveBefore(ctx, req.(*CutoffReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SessionChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SessionChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SessionChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SessionChanges(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SessionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SessionInfo(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_AgentCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).AgentCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_AgentCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).AgentCatalog(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SlashCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SlashCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SlashCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SlashCommands(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SessionModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SessionModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SessionModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SessionModels(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).ListPermissions(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_ListQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).ListQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_ListQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).ListQuestions(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_PermissionRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).PermissionRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_PermissionRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).PermissionRules(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Capabilities(ctx, req.(*PlatformRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Owns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Owns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Owns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Owns(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SendMessage(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).ExecuteCommand(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RunShell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RunShell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RunShell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RunShell(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RespondPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RespondPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RespondPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RespondPermission(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RespondQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RespondQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RespondQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RespondQuestion(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RejectQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RejectQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RejectQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RejectQuestion(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Abort(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RenameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RenameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RenameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RenameSession(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_SetPermissionRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).SetPermissionRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_SetPermissionRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).SetPermissionRules(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Compact(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_ForkSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).ForkSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_ForkSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).ForkSession(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_MoveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).MoveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_MoveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).MoveSession(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformJsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).CreateSession(ctx, req.(*PlatformJsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OcmanServer).StreamEvents(m, &grpc.GenericServerStream[SessionRef, EventChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_StreamEventsServer = grpc.ServerStreamingServer[EventChunk]

func _Ocman_GitInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).GitInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_GitInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).GitInfo(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_GitDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).GitDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_GitDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).GitDiff(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_GitBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).GitBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_GitBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).GitBranches(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_GitCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).GitCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_GitCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).GitCheckout(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_ListWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).ListWorktrees(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_WorktreeDefaultBaseRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).WorktreeDefaultBaseRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_WorktreeDefaultBaseRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).WorktreeDefaultBaseRef(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_CreateWorktreeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).CreateWorktreeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_CreateWorktreeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).CreateWorktreeSession(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RemoveWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RemoveWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RemoveWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RemoveWorktree(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_LaunchTmux_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).LaunchTmux(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_LaunchTmux_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).LaunchTmux(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_EnsureProjectOpencode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).EnsureProjectOpencode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_EnsureProjectOpencode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).EnsureProjectOpencode(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_RestartProjectOpencode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).RestartProjectOpencode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_RestartProjectOpencode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).RestartProjectOpencode(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_TmuxSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).TmuxSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_TmuxSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).TmuxSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_HostCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).HostCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_HostCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).HostCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_TermWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).TermWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_TermWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).TermWindows(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_TermCreateWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).TermCreateWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_TermCreateWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).TermCreateWindow(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_TermKillWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).TermKillWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_TermKillWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).TermKillWindow(ctx, req.(*JsonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_TerminalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OcmanServer).TerminalStream(&grpc.GenericServerStream[TermClientMsg, TermServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_TerminalStreamServer = grpc.BidiStreamingServer[TermClientMsg, TermServerMsg]

func _Ocman_Projects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmanServer).Projects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ocman_Projects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmanServer).Projects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocman_WatchProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OcmanServer).WatchProjects(m, &grpc.GenericServerStream[Empty, JsonResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ocman_WatchProjectsServer = grpc.ServerStreamingServer[JsonResp]

// Ocman_ServiceDesc is the grpc.ServiceDesc for Ocman service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ocman_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocman.remote.v1.Ocman",
	HandlerType: (*OcmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Ocman_Hello_Handler,
		},
		{
			MethodName: "Sessions",
			Handler:    _Ocman_Sessions_Handler,
		},
		{
			MethodName: "Session",
			Handler:    _Ocman_Session_Handler,
		},
		{
			MethodName: "SessionsInactiveBefore",
			Handler:    _Ocman_SessionsInactiveBefore_Handler,
		},
		{
			MethodName: "SessionChanges",
			Handler:    _Ocman_SessionChanges_Handler,
		},
		{
			MethodName: "SessionInfo",
			Handler:    _Ocman_SessionInfo_Handler,
		},
		{
			MethodName: "AgentCatalog",
			Handler:    _Ocman_AgentCatalog_Handler,
		},
		{
			MethodName: "SlashCommands",
			Handler:    _Ocman_SlashCommands_Handler,
		},
		{
			MethodName: "SessionModels",
			Handler:    _Ocman_SessionModels_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _Ocman_ListPermissions_Handler,
		},
		{
			MethodName: "ListQuestions",
			Handler:    _Ocman_ListQuestions_Handler,
		},
		{
			MethodName: "PermissionRules",
			Handler:    _Ocman_PermissionRules_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Ocman_Capabilities_Handler,
		},
		{
			MethodName: "Owns",
			Handler:    _Ocman_Owns_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Ocman_SendMessage_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _Ocman_ExecuteCommand_Handler,
		},
		{
			MethodName: "RunShell",
			Handler:    _Ocman_RunShell_Handler,
		},
		{
			MethodName: "RespondPermission",
			Handler:    _Ocman_RespondPermission_Handler,
		},
		{
			MethodName: "RespondQuestion",
			Handler:    _Ocman_RespondQuestion_Handler,
		},
		{
			MethodName: "RejectQuestion",
			Handler:    _Ocman_RejectQuestion_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _Ocman_Abort_Handler,
		},
		{
			MethodName: "RenameSession",
			Handler:    _Ocman_RenameSession_Handler,
		},
		{
			MethodName: "SetPermissionRules",
			Handler:    _Ocman_SetPermissionRules_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _Ocman_Compact_Handler,
		},
		{
			MethodName: "ForkSession",
			Handler:    _Ocman_ForkSession_Handler,
		},
		{
			MethodName: "MoveSession",
			Handler:    _Ocman_MoveSession_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Ocman_CreateSession_Handler,
		},
		{
			MethodName: "GitInfo",
			Handler:    _Ocman_GitInfo_Handler,
		},
		{
			MethodName: "GitDiff",
			Handler:    _Ocman_GitDiff_Handler,
		},
		{
			MethodName: "GitBranches",
			Handler:    _Ocman_GitBranches_Handler,
		},
		{
			MethodName: "GitCheckout",
			Handler:    _Ocman_GitCheckout_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _Ocman_ListWorktrees_Handler,
		},
		{
			MethodName: "WorktreeDefaultBaseRef",
			Handler:    _Ocman_WorktreeDefaultBaseRef_Handler,
		},
		{
			MethodName: "CreateWorktreeSession",
			Handler:    _Ocman_CreateWorktreeSession_Handler,
		},
		{
			MethodName: "RemoveWorktree",
			Handler:    _Ocman_RemoveWorktree_Handler,
		},
		{
			MethodName: "LaunchTmux",
			Handler:    _Ocman_LaunchTmux_Handler,
		},
		{
			MethodName: "EnsureProjectOpencode",
			Handler:    _Ocman_EnsureProjectOpencode_Handler,
		},
		{
			MethodName: "RestartProjectOpencode",
			Handler:    _Ocman_RestartProjectOpencode_Handler,
		},
		{
			MethodName: "TmuxSessions",
			Handler:    _Ocman_TmuxSessions_Handler,
		},
		{
			MethodName: "HostCapabilities",
			Handler:    _Ocman_HostCapabilities_Handler,
		},
		{
			MethodName: "TermWindows",
			Handler:    _Ocman_TermWindows_Handler,
		},
		{
			MethodName: "TermCreateWindow",
			Handler:    _Ocman_TermCreateWindow_Handler,
		},
		{
			MethodName: "TermKillWindow",
			Handler:    _Ocman_TermKillWindow_Handler,
		},
		{
			MethodName: "Projects",
			Handler:    _Ocman_Projects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Ocman_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TerminalStream",
			Handler:       _Ocman_TerminalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchProjects",
			Handler:       _Ocman_WatchProjects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/remote/proto/remote.proto",
}
