// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/remote/proto/remote.proto

package remotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{0}
}

type HelloReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReq) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type HelloResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	InstanceId      string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OcmanVersion    string                 `protobuf:"bytes,4,opt,name=ocman_version,json=ocmanVersion,proto3" json:"ocman_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResp) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloResp) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HelloResp) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HelloResp) GetOcmanVersion() string {
	if x != nil {
		return x.OcmanVersion
	}
	return ""
}

// PlatformRef carries the base platform id.
type PlatformRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformRef) Reset() {
	*x = PlatformRef{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRef) ProtoMessage() {}

func (x *PlatformRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRef.ProtoReflect.Descriptor instead.
func (*PlatformRef) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{3}
}

func (x *PlatformRef) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// SessionRef carries the base platform id plus a session id.
type SessionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRef) Reset() {
	*x = SessionRef{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRef) ProtoMessage() {}

func (x *SessionRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRef.ProtoReflect.Descriptor instead.
func (*SessionRef) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{4}
}

func (x *SessionRef) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsReq) Reset() {
	*x = SessionsReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsReq) ProtoMessage() {}

func (x *SessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsReq.ProtoReflect.Descriptor instead.
func (*SessionsReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{5}
}

func (x *SessionsReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionsReq) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *SessionsReq) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type SessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReq) Reset() {
	*x = SessionReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReq) ProtoMessage() {}

func (x *SessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReq.ProtoReflect.Descriptor instead.
func (*SessionReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{6}
}

func (x *SessionReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SessionReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CutoffReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Cutoff        int64                  `protobuf:"varint,2,opt,name=cutoff,proto3" json:"cutoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutoffReq) Reset() {
	*x = CutoffReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutoffReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutoffReq) ProtoMessage() {}

func (x *CutoffReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutoffReq.ProtoReflect.Descriptor instead.
func (*CutoffReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{7}
}

func (x *CutoffReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CutoffReq) GetCutoff() int64 {
	if x != nil {
		return x.Cutoff
	}
	return 0
}

// JsonResp / JsonReq wrap an opaque JSON payload (AD-11).
type JsonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResp) Reset() {
	*x = JsonResp{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResp) ProtoMessage() {}

func (x *JsonResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResp.ProtoReflect.Descriptor instead.
func (*JsonResp) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{8}
}

func (x *JsonResp) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JsonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonReq) Reset() {
	*x = JsonReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonReq) ProtoMessage() {}

func (x *JsonReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonReq.ProtoReflect.Descriptor instead.
func (*JsonReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{9}
}

func (x *JsonReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PlatformJsonReq carries a base platform id plus a JSON request body
// (for the mutating Platform RPCs whose request structs are rich types).
type PlatformJsonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformJsonReq) Reset() {
	*x = PlatformJsonReq{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformJsonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformJsonReq) ProtoMessage() {}

func (x *PlatformJsonReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformJsonReq.ProtoReflect.Descriptor instead.
func (*PlatformJsonReq) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{10}
}

func (x *PlatformJsonReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformJsonReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OwnsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owns          bool                   `protobuf:"varint,1,opt,name=owns,proto3" json:"owns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnsResp) Reset() {
	*x = OwnsResp{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnsResp) ProtoMessage() {}

func (x *OwnsResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnsResp.ProtoReflect.Descriptor instead.
func (*OwnsResp) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{11}
}

func (x *OwnsResp) GetOwns() bool {
	if x != nil {
		return x.Owns
	}
	return false
}

type EventChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventChunk) Reset() {
	*x = EventChunk{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChunk) ProtoMessage() {}

func (x *EventChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChunk.ProtoReflect.Descriptor instead.
func (*EventChunk) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{12}
}

func (x *EventChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TermClientMsg is a hub->remote terminal frame. The first message on a
// TerminalStream MUST carry `open` to select the target window; later
// messages carry `data` (raw keystrokes) or `resize`.
type TermClientMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          *TermOpen              `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Resize        *TermResize            `protobuf:"bytes,3,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermClientMsg) Reset() {
	*x = TermClientMsg{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermClientMsg) ProtoMessage() {}

func (x *TermClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermClientMsg.ProtoReflect.Descriptor instead.
func (*TermClientMsg) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{13}
}

func (x *TermClientMsg) GetOpen() *TermOpen {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *TermClientMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TermClientMsg) GetResize() *TermResize {
	if x != nil {
		return x.Resize
	}
	return nil
}

type TermOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermOpen) Reset() {
	*x = TermOpen{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermOpen) ProtoMessage() {}

func (x *TermOpen) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermOpen.ProtoReflect.Descriptor instead.
func (*TermOpen) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{14}
}

func (x *TermOpen) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *TermOpen) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *TermOpen) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type TermResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermResize) Reset() {
	*x = TermResize{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermResize) ProtoMessage() {}

func (x *TermResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermResize.ProtoReflect.Descriptor instead.
func (*TermResize) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{15}
}

func (x *TermResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TermResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// TermServerMsg is a remote->hub terminal frame carrying PTY output.
type TermServerMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermServerMsg) Reset() {
	*x = TermServerMsg{}
	mi := &file_internal_remote_proto_remote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermServerMsg) ProtoMessage() {}

func (x *TermServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_remote_proto_remote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermServerMsg.ProtoReflect.Descriptor instead.
func (*TermServerMsg) Descriptor() ([]byte, []int) {
	return file_internal_remote_proto_remote_proto_rawDescGZIP(), []int{16}
}

func (x *TermServerMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_remote_proto_remote_proto protoreflect.FileDescriptor

const file_internal_remote_proto_remote_proto_rawDesc = "" +
	"\n" +
	"\"internal/remote/proto/remote.proto\x12\x0focman.remote.v1\"\a\n" +
	"\x05Empty\"5\n" +
	"\bHelloReq\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\"\x98\x01\n" +
	"\tHelloResp\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\rocman_version\x18\x04 \x01(\tR\focmanVersion\")\n" +
	"\vPlatformRef\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"G\n" +
	"\n" +
	"SessionRef\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"Q\n" +
	"\vSessionsReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\"u\n" +
	"\n" +
	"SessionReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"?\n" +
	"\tCutoffReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06cutoff\x18\x02 \x01(\x03R\x06cutoff\"$\n" +
	"\bJsonResp\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"#\n" +
	"\aJsonReq\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"G\n" +
	"\x0fPlatformJsonReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x1e\n" +
	"\bOwnsResp\x12\x12\n" +
	"\x04owns\x18\x01 \x01(\bR\x04owns\" \n" +
	"\n" +
	"EventChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x87\x01\n" +
	"\rTermClientMsg\x12-\n" +
	"\x04open\x18\x01 \x01(\v2\x19.ocman.remote.v1.TermOpenR\x04open\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x123\n" +
	"\x06resize\x18\x03 \x01(\v2\x1b.ocman.remote.v1.TermResizeR\x06resize\"P\n" +
	"\bTermOpen\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"4\n" +
	"\n" +
	"TermResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"#\n" +
	"\rTermServerMsg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xe6\x18\n" +
	"\x05Ocman\x12>\n" +
	"\x05Hello\x12\x19.ocman.remote.v1.HelloReq\x1a\x1a.ocman.remote.v1.HelloResp\x12C\n" +
	"\bSessions\x12\x1c.ocman.remote.v1.SessionsReq\x1a\x19.ocman.remote.v1.JsonResp\x12A\n" +
	"\aSession\x12\x1b.ocman.remote.v1.SessionReq\x1a\x19.ocman.remote.v1.JsonResp\x12O\n" +
	"\x16SessionsInactiveBefore\x12\x1a.ocman.remote.v1.CutoffReq\x1a\x19.ocman.remote.v1.JsonResp\x12H\n" +
	"\x0eSessionChanges\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12E\n" +
	"\vSessionInfo\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12F\n" +
	"\fAgentCatalog\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12G\n" +
	"\rSlashCommands\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12G\n" +
	"\rSessionModels\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12I\n" +
	"\x0fListPermissions\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12G\n" +
	"\rListQuestions\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12I\n" +
	"\x0fPermissionRules\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonResp\x12G\n" +
	"\fCapabilities\x12\x1c.ocman.remote.v1.PlatformRef\x1a\x19.ocman.remote.v1.JsonResp\x12>\n" +
	"\x04Owns\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.OwnsResp\x12G\n" +
	"\vSendMessage\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12J\n" +
	"\x0eExecuteCommand\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12D\n" +
	"\bRunShell\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12M\n" +
	"\x11RespondPermission\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12K\n" +
	"\x0fRespondQuestion\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12J\n" +
	"\x0eRejectQuestion\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12A\n" +
	"\x05Abort\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12I\n" +
	"\rRenameSession\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12N\n" +
	"\x12SetPermissionRules\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12C\n" +
	"\aCompact\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x16.ocman.remote.v1.Empty\x12L\n" +
	"\rCreateSession\x12 .ocman.remote.v1.PlatformJsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12J\n" +
	"\fStreamEvents\x12\x1b.ocman.remote.v1.SessionRef\x1a\x1b.ocman.remote.v1.EventChunk0\x01\x12>\n" +
	"\aGitInfo\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12>\n" +
	"\aGitDiff\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12B\n" +
	"\vGitBranches\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12?\n" +
	"\vGitCheckout\x12\x18.ocman.remote.v1.JsonReq\x1a\x16.ocman.remote.v1.Empty\x12D\n" +
	"\rListWorktrees\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12M\n" +
	"\x16WorktreeDefaultBaseRef\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12L\n" +
	"\x15CreateWorktreeSession\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12B\n" +
	"\x0eRemoveWorktree\x12\x18.ocman.remote.v1.JsonReq\x1a\x16.ocman.remote.v1.Empty\x12A\n" +
	"\n" +
	"LaunchTmux\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12L\n" +
	"\x15EnsureProjectOpencode\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12A\n" +
	"\fTmuxSessions\x12\x16.ocman.remote.v1.Empty\x1a\x19.ocman.remote.v1.JsonResp\x12E\n" +
	"\x10HostCapabilities\x12\x16.ocman.remote.v1.Empty\x1a\x19.ocman.remote.v1.JsonResp\x12B\n" +
	"\vTermWindows\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12G\n" +
	"\x10TermCreateWindow\x12\x18.ocman.remote.v1.JsonReq\x1a\x19.ocman.remote.v1.JsonResp\x12B\n" +
	"\x0eTermKillWindow\x12\x18.ocman.remote.v1.JsonReq\x1a\x16.ocman.remote.v1.Empty\x12T\n" +
	"\x0eTerminalStream\x12\x1e.ocman.remote.v1.TermClientMsg\x1a\x1e.ocman.remote.v1.TermServerMsg(\x010\x01\x12=\n" +
	"\bProjects\x12\x16.ocman.remote.v1.Empty\x1a\x19.ocman.remote.v1.JsonResp\x12D\n" +
	"\rWatchProjects\x12\x16.ocman.remote.v1.Empty\x1a\x19.ocman.remote.v1.JsonResp0\x01B<Z:github.com/NoUseFreak/ocman/internal/remote/proto;remotepbb\x06proto3"

var (
	file_internal_remote_proto_remote_proto_rawDescOnce sync.Once
	file_internal_remote_proto_remote_proto_rawDescData []byte
)

func file_internal_remote_proto_remote_proto_rawDescGZIP() []byte {
	file_internal_remote_proto_remote_proto_rawDescOnce.Do(func() {
		file_internal_remote_proto_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_remote_proto_remote_proto_rawDesc), len(file_internal_remote_proto_remote_proto_rawDesc)))
	})
	return file_internal_remote_proto_remote_proto_rawDescData
}

var file_internal_remote_proto_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_remote_proto_remote_proto_goTypes = []any{
	(*Empty)(nil),           // 0: ocman.remote.v1.Empty
	(*HelloReq)(nil),        // 1: ocman.remote.v1.HelloReq
	(*HelloResp)(nil),       // 2: ocman.remote.v1.HelloResp
	(*PlatformRef)(nil),     // 3: ocman.remote.v1.PlatformRef
	(*SessionRef)(nil),      // 4: ocman.remote.v1.SessionRef
	(*SessionsReq)(nil),     // 5: ocman.remote.v1.SessionsReq
	(*SessionReq)(nil),      // 6: ocman.remote.v1.SessionReq
	(*CutoffReq)(nil),       // 7: ocman.remote.v1.CutoffReq
	(*JsonResp)(nil),        // 8: ocman.remote.v1.JsonResp
	(*JsonReq)(nil),         // 9: ocman.remote.v1.JsonReq
	(*PlatformJsonReq)(nil), // 10: ocman.remote.v1.PlatformJsonReq
	(*OwnsResp)(nil),        // 11: ocman.remote.v1.OwnsResp
	(*EventChunk)(nil),      // 12: ocman.remote.v1.EventChunk
	(*TermClientMsg)(nil),   // 13: ocman.remote.v1.TermClientMsg
	(*TermOpen)(nil),        // 14: ocman.remote.v1.TermOpen
	(*TermResize)(nil),      // 15: ocman.remote.v1.TermResize
	(*TermServerMsg)(nil),   // 16: ocman.remote.v1.TermServerMsg
}
var file_internal_remote_proto_remote_proto_depIdxs = []int32{
	14, // 0: ocman.remote.v1.TermClientMsg.open:type_name -> ocman.remote.v1.TermOpen
	15, // 1: ocman.remote.v1.TermClientMsg.resize:type_name -> ocman.remote.v1.TermResize
	1,  // 2: ocman.remote.v1.Ocman.Hello:input_type -> ocman.remote.v1.HelloReq
	5,  // 3: ocman.remote.v1.Ocman.Sessions:input_type -> ocman.remote.v1.SessionsReq
	6,  // 4: ocman.remote.v1.Ocman.Session:input_type -> ocman.remote.v1.SessionReq
	7,  // 5: ocman.remote.v1.Ocman.SessionsInactiveBefore:input_type -> ocman.remote.v1.CutoffReq
	4,  // 6: ocman.remote.v1.Ocman.SessionChanges:input_type -> ocman.remote.v1.SessionRef
	4,  // 7: ocman.remote.v1.Ocman.SessionInfo:input_type -> ocman.remote.v1.SessionRef
	4,  // 8: ocman.remote.v1.Ocman.AgentCatalog:input_type -> ocman.remote.v1.SessionRef
	4,  // 9: ocman.remote.v1.Ocman.SlashCommands:input_type -> ocman.remote.v1.SessionRef
	4,  // 10: ocman.remote.v1.Ocman.SessionModels:input_type -> ocman.remote.v1.SessionRef
	4,  // 11: ocman.remote.v1.Ocman.ListPermissions:input_type -> ocman.remote.v1.SessionRef
	4,  // 12: ocman.remote.v1.Ocman.ListQuestions:input_type -> ocman.remote.v1.SessionRef
	4,  // 13: ocman.remote.v1.Ocman.PermissionRules:input_type -> ocman.remote.v1.SessionRef
	3,  // 14: ocman.remote.v1.Ocman.Capabilities:input_type -> ocman.remote.v1.PlatformRef
	4,  // 15: ocman.remote.v1.Ocman.Owns:input_type -> ocman.remote.v1.SessionRef
	10, // 16: ocman.remote.v1.Ocman.SendMessage:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 17: ocman.remote.v1.Ocman.ExecuteCommand:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 18: ocman.remote.v1.Ocman.RunShell:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 19: ocman.remote.v1.Ocman.RespondPermission:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 20: ocman.remote.v1.Ocman.RespondQuestion:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 21: ocman.remote.v1.Ocman.RejectQuestion:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 22: ocman.remote.v1.Ocman.Abort:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 23: ocman.remote.v1.Ocman.RenameSession:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 24: ocman.remote.v1.Ocman.SetPermissionRules:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 25: ocman.remote.v1.Ocman.Compact:input_type -> ocman.remote.v1.PlatformJsonReq
	10, // 26: ocman.remote.v1.Ocman.CreateSession:input_type -> ocman.remote.v1.PlatformJsonReq
	4,  // 27: ocman.remote.v1.Ocman.StreamEvents:input_type -> ocman.remote.v1.SessionRef
	9,  // 28: ocman.remote.v1.Ocman.GitInfo:input_type -> ocman.remote.v1.JsonReq
	9,  // 29: ocman.remote.v1.Ocman.GitDiff:input_type -> ocman.remote.v1.JsonReq
	9,  // 30: ocman.remote.v1.Ocman.GitBranches:input_type -> ocman.remote.v1.JsonReq
	9,  // 31: ocman.remote.v1.Ocman.GitCheckout:input_type -> ocman.remote.v1.JsonReq
	9,  // 32: ocman.remote.v1.Ocman.ListWorktrees:input_type -> ocman.remote.v1.JsonReq
	9,  // 33: ocman.remote.v1.Ocman.WorktreeDefaultBaseRef:input_type -> ocman.remote.v1.JsonReq
	9,  // 34: ocman.remote.v1.Ocman.CreateWorktreeSession:input_type -> ocman.remote.v1.JsonReq
	9,  // 35: ocman.remote.v1.Ocman.RemoveWorktree:input_type -> ocman.remote.v1.JsonReq
	9,  // 36: ocman.remote.v1.Ocman.LaunchTmux:input_type -> ocman.remote.v1.JsonReq
	9,  // 37: ocman.remote.v1.Ocman.EnsureProjectOpencode:input_type -> ocman.remote.v1.JsonReq
	0,  // 38: ocman.remote.v1.Ocman.TmuxSessions:input_type -> ocman.remote.v1.Empty
	0,  // 39: ocman.remote.v1.Ocman.HostCapabilities:input_type -> ocman.remote.v1.Empty
	9,  // 40: ocman.remote.v1.Ocman.TermWindows:input_type -> ocman.remote.v1.JsonReq
	9,  // 41: ocman.remote.v1.Ocman.TermCreateWindow:input_type -> ocman.remote.v1.JsonReq
	9,  // 42: ocman.remote.v1.Ocman.TermKillWindow:input_type -> ocman.remote.v1.JsonReq
	13, // 43: ocman.remote.v1.Ocman.TerminalStream:input_type -> ocman.remote.v1.TermClientMsg
	0,  // 44: ocman.remote.v1.Ocman.Projects:input_type -> ocman.remote.v1.Empty
	0,  // 45: ocman.remote.v1.Ocman.WatchProjects:input_type -> ocman.remote.v1.Empty
	2,  // 46: ocman.remote.v1.Ocman.Hello:output_type -> ocman.remote.v1.HelloResp
	8,  // 47: ocman.remote.v1.Ocman.Sessions:output_type -> ocman.remote.v1.JsonResp
	8,  // 48: ocman.remote.v1.Ocman.Session:output_type -> ocman.remote.v1.JsonResp
	8,  // 49: ocman.remote.v1.Ocman.SessionsInactiveBefore:output_type -> ocman.remote.v1.JsonResp
	8,  // 50: ocman.remote.v1.Ocman.SessionChanges:output_type -> ocman.remote.v1.JsonResp
	8,  // 51: ocman.remote.v1.Ocman.SessionInfo:output_type -> ocman.remote.v1.JsonResp
	8,  // 52: ocman.remote.v1.Ocman.AgentCatalog:output_type -> ocman.remote.v1.JsonResp
	8,  // 53: ocman.remote.v1.Ocman.SlashCommands:output_type -> ocman.remote.v1.JsonResp
	8,  // 54: ocman.remote.v1.Ocman.SessionModels:output_type -> ocman.remote.v1.JsonResp
	8,  // 55: ocman.remote.v1.Ocman.ListPermissions:output_type -> ocman.remote.v1.JsonResp
	8,  // 56: ocman.remote.v1.Ocman.ListQuestions:output_type -> ocman.remote.v1.JsonResp
	8,  // 57: ocman.remote.v1.Ocman.PermissionRules:output_type -> ocman.remote.v1.JsonResp
	8,  // 58: ocman.remote.v1.Ocman.Capabilities:output_type -> ocman.remote.v1.JsonResp
	11, // 59: ocman.remote.v1.Ocman.Owns:output_type -> ocman.remote.v1.OwnsResp
	0,  // 60: ocman.remote.v1.Ocman.SendMessage:output_type -> ocman.remote.v1.Empty
	0,  // 61: ocman.remote.v1.Ocman.ExecuteCommand:output_type -> ocman.remote.v1.Empty
	0,  // 62: ocman.remote.v1.Ocman.RunShell:output_type -> ocman.remote.v1.Empty
	0,  // 63: ocman.remote.v1.Ocman.RespondPermission:output_type -> ocman.remote.v1.Empty
	0,  // 64: ocman.remote.v1.Ocman.RespondQuestion:output_type -> ocman.remote.v1.Empty
	0,  // 65: ocman.remote.v1.Ocman.RejectQuestion:output_type -> ocman.remote.v1.Empty
	0,  // 66: ocman.remote.v1.Ocman.Abort:output_type -> ocman.remote.v1.Empty
	0,  // 67: ocman.remote.v1.Ocman.RenameSession:output_type -> ocman.remote.v1.Empty
	0,  // 68: ocman.remote.v1.Ocman.SetPermissionRules:output_type -> ocman.remote.v1.Empty
	0,  // 69: ocman.remote.v1.Ocman.Compact:output_type -> ocman.remote.v1.Empty
	8,  // 70: ocman.remote.v1.Ocman.CreateSession:output_type -> ocman.remote.v1.JsonResp
	12, // 71: ocman.remote.v1.Ocman.StreamEvents:output_type -> ocman.remote.v1.EventChunk
	8,  // 72: ocman.remote.v1.Ocman.GitInfo:output_type -> ocman.remote.v1.JsonResp
	8,  // 73: ocman.remote.v1.Ocman.GitDiff:output_type -> ocman.remote.v1.JsonResp
	8,  // 74: ocman.remote.v1.Ocman.GitBranches:output_type -> ocman.remote.v1.JsonResp
	0,  // 75: ocman.remote.v1.Ocman.GitCheckout:output_type -> ocman.remote.v1.Empty
	8,  // 76: ocman.remote.v1.Ocman.ListWorktrees:output_type -> ocman.remote.v1.JsonResp
	8,  // 77: ocman.remote.v1.Ocman.WorktreeDefaultBaseRef:output_type -> ocman.remote.v1.JsonResp
	8,  // 78: ocman.remote.v1.Ocman.CreateWorktreeSession:output_type -> ocman.remote.v1.JsonResp
	0,  // 79: ocman.remote.v1.Ocman.RemoveWorktree:output_type -> ocman.remote.v1.Empty
	8,  // 80: ocman.remote.v1.Ocman.LaunchTmux:output_type -> ocman.remote.v1.JsonResp
	8,  // 81: ocman.remote.v1.Ocman.EnsureProjectOpencode:output_type -> ocman.remote.v1.JsonResp
	8,  // 82: ocman.remote.v1.Ocman.TmuxSessions:output_type -> ocman.remote.v1.JsonResp
	8,  // 83: ocman.remote.v1.Ocman.HostCapabilities:output_type -> ocman.remote.v1.JsonResp
	8,  // 84: ocman.remote.v1.Ocman.TermWindows:output_type -> ocman.remote.v1.JsonResp
	8,  // 85: ocman.remote.v1.Ocman.TermCreateWindow:output_type -> ocman.remote.v1.JsonResp
	0,  // 86: ocman.remote.v1.Ocman.TermKillWindow:output_type -> ocman.remote.v1.Empty
	16, // 87: ocman.remote.v1.Ocman.TerminalStream:output_type -> ocman.remote.v1.TermServerMsg
	8,  // 88: ocman.remote.v1.Ocman.Projects:output_type -> ocman.remote.v1.JsonResp
	8,  // 89: ocman.remote.v1.Ocman.WatchProjects:output_type -> ocman.remote.v1.JsonResp
	46, // [46:90] is the sub-list for method output_type
	2,  // [2:46] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_remote_proto_remote_proto_init() }
func file_internal_remote_proto_remote_proto_init() {
	if File_internal_remote_proto_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_remote_proto_remote_proto_rawDesc), len(file_internal_remote_proto_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_remote_proto_remote_proto_goTypes,
		DependencyIndexes: file_internal_remote_proto_remote_proto_depIdxs,
		MessageInfos:      file_internal_remote_proto_remote_proto_msgTypes,
	}.Build()
	File_internal_remote_proto_remote_proto = out.File
	file_internal_remote_proto_remote_proto_goTypes = nil
	file_internal_remote_proto_remote_proto_depIdxs = nil
}
