// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/remote/proto/usage.proto

package remotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_remote_proto_usage_proto protoreflect.FileDescriptor

const file_internal_remote_proto_usage_proto_rawDesc = "" +
	"\n" +
	"!internal/remote/proto/usage.proto\x12\x0focman.remote.v1\x1a\"internal/remote/proto/remote.proto2O\n" +
	"\x05Usage\x12F\n" +
	"\fSessionUsage\x12\x1b.ocman.remote.v1.SessionRef\x1a\x19.ocman.remote.v1.JsonRespB<Z:github.com/NoUseFreak/ocman/internal/remote/proto;remotepbb\x06proto3"

var file_internal_remote_proto_usage_proto_goTypes = []any{
	(*SessionRef)(nil), // 0: ocman.remote.v1.SessionRef
	(*JsonResp)(nil),   // 1: ocman.remote.v1.JsonResp
}
var file_internal_remote_proto_usage_proto_depIdxs = []int32{
	0, // 0: ocman.remote.v1.Usage.SessionUsage:input_type -> ocman.remote.v1.SessionRef
	1, // 1: ocman.remote.v1.Usage.SessionUsage:output_type -> ocman.remote.v1.JsonResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_remote_proto_usage_proto_init() }
func file_internal_remote_proto_usage_proto_init() {
	if File_internal_remote_proto_usage_proto != nil {
		return
	}
	file_internal_remote_proto_remote_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_remote_proto_usage_proto_rawDesc), len(file_internal_remote_proto_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_remote_proto_usage_proto_goTypes,
		DependencyIndexes: file_internal_remote_proto_usage_proto_depIdxs,
	}.Build()
	File_internal_remote_proto_usage_proto = out.File
	file_internal_remote_proto_usage_proto_goTypes = nil
	file_internal_remote_proto_usage_proto_depIdxs = nil
}
